--- #YAML:1.0
name: Crypt-SHAVS
version: 0.02
abstract: Interface to NIST SHA Validation System
license: perl
author:
  - Mark Shelor, mshelor@cpan.org
requires:
  perl: 5.003
provides:
  Crypt::SHAVS:
    file: lib/Crypt/SHAVS.pm
    version: 0.02
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Mark Shelor
